### ISSUE TITLE
job terminated even when running on one machine

### ISSUE THREAD

**Issue by Brandonage** [msimonin/vagrant-g5k#12]
Thanks for the update on #11 . Everything runs more smoothly now and I don't get that many machines going down. All the jobs are run in one machine now instead of multiple machines. However sometimes I still get the same error, even if the job is running on a single machine. I attach here one example

abrandon@fnancy:~$ oarstat -j 1282350 -f
Job_Id: 1282350
    job_array_id = 1282350
    job_array_index = 1
    name = test-2
    project = default
    owner = abrandon
    state = Terminated
    wanted_resources = -l "{(virtual != 'none') AND type = 'default'}/host=1/core=2,walltime=12:0:0"
    types =
    dependencies =
    assigned_resources = 2647+2648
    assigned_hostnames = graphene-125.nancy.grid5000.fr
    queue = default
    command = .vagrant/test-vagrant-g5k/launch_vm.sh 2 12288 BRIDGE .vagrant/test-vagrant-g5k/subnet -drive file=/home/abrandon/public/centos_7.2_dcos.qcow2,if=virtio -snapshot
    exit_code = 0 (0,0,0)
    launchingDirectory = /home/abrandon
    stdout_file = OAR.test-2.1282350.stdout
    stderr_file = OAR.test-2.1282350.stderr
    jobType = PASSIVE
    properties = (maintenance = 'NO') AND production = 'NO'
    reservation = None
    walltime = 12:0:0
    submissionTime = 2017-06-20 13:37:23
    startTime = 2017-06-20 13:37:28
    stopTime = 2017-06-20 18:28:43
    cpuset_name = abrandon_1282350
    initial_request = oarsub --json -l {virtual != 'none'}/nodes=1/core=2, walltime=12:00:00 --name test-2 --checkpoint 60 --signal 12 .vagrant/test-vagrant-g5k/launch_vm.sh 2 12288 BRIDGE .vagrant/test-vagrant-g5k/subnet -drive file=/home/abrandon/public/centos_7.2_dcos.qcow2,if=virtio -snapshot
    message = FIFO scheduling OK
    scheduledStart = no prediction
    resubmit_job_id = 0
    events =
2017-06-20 18:28:45> SWITCH_INTO_TERMINATE_STATE:[bipbip 1282350] Ask to change the job state

**Comment by msimonin** [comment]
Could you check the content of the two files `OAR.test-2.1282350.stdout` and `OAR.test-2.1282350.stderr`?

**Comment by Brandonage** [comment]
Ahh sorry they are gone. I'll try to keep them if I bump into the same problem

**Comment by Brandonage** [comment]
Ok. I do have them now for a deployment I made in rennes where two machines went down.



[OAR.test-8.923952.stderr.txt](https://github.com/msimonin/vagrant-g5k/files/1091008/OAR.test-8.923952.stderr.txt)
[OAR.test-8.923952.stdout.txt](https://github.com/msimonin/vagrant-g5k/files/1091005/OAR.test-8.923952.stdout.txt)
[OAR.test-12.923956.stderr.txt](https://github.com/msimonin/vagrant-g5k/files/1091007/OAR.test-12.923956.stderr.txt)
[OAR.test-12.923956.stdout.txt](https://github.com/msimonin/vagrant-g5k/files/1091006/OAR.test-12.923956.stdout.txt)

**Comment by msimonin** [comment]
in the stderr I see : 
```
.vagrant/test-vagrant-g5k/launch_vm.sh: line 84:  2843 Killed
```
but I don't have any clue to explain it ...

**Comment by Brandonage** [comment]
So this means that the same script that launches the VM's kills the Job in g5k?

**Comment by Brandonage** [comment]
I think this is related to the VM's using more resources from the host than it should and getting killed. I'm using CentOS and sometimes I was getting messages like: 

BUG: soft lockup - CPU#3 stuck for 22s!

I recently increased the number of cores to 4 for my experiments and they are working fine now *touches wood 🙄 *

What I still don't know is who sends the kill signal to the launch_vm.sh script.

**Comment by msimonin** [comment]
any updates :) ?

**Comment by Brandonage** [comment]
Sorry Matthieu, I thought I told you about this. I think that the VM was
using more resources than it should and then something was killing the
script .vagrant/test-vagrant-g5k/launch_vm.sh that kept the VM up.

Whatever the case I solved it by increasing the number of cores from 3 to
4. I'm also getting some ugly messages when vagrant up finishes. I paste
them below. All and all I'm being able to spin 75 VM's in minutes with
these, so thanks for developing this plugin!.

==> test-1: An error occurred. The error will be shown after all tasks
complete.
==> test-3: Machine booted and ready!
==> test-5: An error occurred. The error will be shown after all tasks
complete.
==> test-6: Machine booted and ready!
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An unexpected error occurred when executing the action on the
'test-1' machine. Please report this as a bug:

Broken pipe

/opt/vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/transport/server_version.rb:44:in
`write'
/opt/vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/transport/server_version.rb:44:in
`negotiate!'
/opt/vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/transport/server_version.rb:32:in
`initialize'
/opt/vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/transport/session.rb:84:in
`new'
/opt/vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/transport/session.rb:84:in
`initialize'
/opt/vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh.rb:233:in `new'
/opt/vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh.rb:233:in `start'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.5/plugins/communicators/ssh/communicator.rb:399:in
`block (2 levels) in connect'
/opt/vagrant/embedded/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
/opt/vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `block in catch'
/opt/vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `catch'
/opt/vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `catch'
/opt/vagrant/embedded/lib/ruby/2.2.0/timeout.rb:103:in `timeout'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.5/plugins/communicators/ssh/communicator.rb:373:in
`block in connect'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/util/retryable.rb:17:in
`retryable'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.5/plugins/communicators/ssh/communicator.rb:372:in
`connect'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.5/plugins/communicators/ssh/communicator.rb:82:in
`block in wait_for_ready'
/opt/vagrant/embedded/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
/opt/vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `block in catch'
/opt/vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `catch'
/opt/vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `catch'
/opt/vagrant/embedded/lib/ruby/2.2.0/timeout.rb:103:in `timeout'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.5/plugins/communicators/ssh/communicator.rb:60:in
`wait_for_ready'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/builtin/wait_for_communicator.rb:16:in
`block in call'

An unexpected error occurred when executing the action on the
'test-5' machine. Please report this as a bug:


2017-09-12 22:17 GMT+02:00 Matthieu Simonin <notifications@github.com>:

**Comment by msimonin** [comment]
Hi @Brandonage, 

I just wanted to know if I could close the issue.
It seems so and I'm glad you manage to start your VMs :) 

Thanks for your feedbacks, let's see where this plugin will lead us !
