### ISSUE TITLE
The provider g5k could not be found

### ISSUE THREAD

**Issue by Brandonage** [msimonin/vagrant-g5k#13]
Hello:

When trying to start the provisioning of VM's I get the following error.

usuariop87:vagrant-g5k alvarobrandon$ vagrant up --provider=g5k
The provider 'g5k' could not be found, but was requested to
back the machine 'test-1'. Please use a provider that exists.

This is the first time it happens and I didn't change anything on the Vagrantfile

**Comment by msimonin** [comment]
Which version of vagrant/virtualbox/vagrant-g5k are you using ?

**Comment by Brandonage** [comment]
I fixed it by reinstalling the plugin. Weird 😕 . Sorry about the noise

**Comment by msimonin** [comment]
FYI, the latest `vagrant-g5k:0.9.6` should be (only) compatible with `vagrant:1.9.5`

**Comment by Brandonage** [comment]
I actually have vagrant-g5k (0.9.7) installed. Is this the intended last
version?

2017-06-28 11:24 GMT+02:00 Matthieu Simonin <notifications@github.com>:
