### ISSUE TITLE
Port forwarding

### ISSUE THREAD

**Issue by david-guyon** [msimonin/vagrant-g5k#4]
Hi Matthieu, 

Let's say I have a web application running on my VM on port 8080 and I want to get an access to this app from the outside. According to this [line](https://github.com/msimonin/vagrant-g5k/blob/master/Vagrantfile#L42) I can write something like:

    g5k.ports = ['2222-:22', '8080-:8080']

Now my VM should forward its 8080 port to its host (a g5k node). With a SSH tunnel I should be able to access that application with something like: 

    ssh -NL 8080:myNode.theSite.g5k:8080 myUsername@myNode.theSite.g5k

Unfortunatly I'm getting this error each time I try to access the page: 

> channel 2: open failed: administratively prohibited: open failed

My few questions:

- Why the dash ('2222-') in the port forwarding configuration?
- Am I doing it right (the port forwarding configuration)?
- Am I doing it right (the SSH tunnel)?

Because others may need this feature, it would be great to give an example in the README file. 
Thanks in advance.

**Comment by msimonin** [comment]
You're not mistaken and it should work.
Can you try with the following tunnel creation  : 

```
ssh -NL 8080:parapluie-1.rennes.grid5000.fr:8080 access.grid5000.fr
```

asssuming parapluie-1 is the node hosting the VM.

**Comment by david-guyon** [comment]
Like this it is not working, I changed `access.grid5000.fr` to `access.g5k` in order to use my SSH configuration. Now I don't get the _Permission denied (publickey)_ error. In the end my command looks like this:

```
ssh -NL 8080:taurus-6.lyon.grid5000.fr:8080 access.g5k
```

It works pretty well. Thank you for the quick answer!

**Comment by msimonin** [comment]
Glad to see it works ! :)
