### ISSUE TITLE
Remote command error on rennes

### ISSUE THREAD

**Issue by Brandonage** [msimonin/vagrant-g5k#9]
Hello: 

When trying to deploy in rennes a set of virtual machines I get the following message

```
usuariop87:vagrant-g5k alvarobrandon$ vagrant up --provider=g5k
Remote command error
```

I can still deploy on other frontends so there is not rush :) I just wanted to check if there is any issue in rennes.

**Comment by msimonin** [comment]
Don't know about Rennes, but you can have more output with : 

```VAGRANT_LOG=debug vagrant up --provider=g5k```

**Comment by Brandonage** [comment]
Thanks!. That definitely narrows down the problem. The error comes from executing oarstat
```
DEBUG driver: Executing oarstat --json -j 1755939
ERROR driver: Hash: {:stderr=>"hash- or arrayref expected (not a simple scalar, use allow_nonref to allow this) at /usr/lib/oar/oarstat line 285.", :code=>255}
```

I attach the full log too

[vagrant_rennes.txt](https://github.com/msimonin/vagrant-g5k/files/1058285/vagrant_rennes.txt)

**Comment by msimonin** [comment]
I think I remember that `oarstat --json` fails when there is no job at all. You have maybe faced this unlikely situation.

**Comment by Brandonage** [comment]
Yep. Somehow the .vagrant directory was still there after destroying the deployment and it was trying to connect to the same job. It's weir because it never happened before
